// solve.js: find a route through the whole level and write it to src/route.js.
//   node tools/solve.js            write the route
//   node tools/solve.js --check    fail if the stored route no longer finishes
// The route powers ?autoplay and the tests' proof that the level can be
// finished; the solver is in solver.js.
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const L = require('../src/node.js');
const S = require('./solver.js');
const file = path.join(__dirname, '..', 'src', 'route.js');

function encode(inputs) {
  const runs = [];
  let cur = 0, n = 0;
  for (const v of inputs) { if (v === cur) n++; else { runs.push(n); cur = v; n = 1; } }
  runs.push(n);
  return runs.map(r => r.toString(36)).join(',');
}

const lv = L.buildLevel();
if (process.argv.includes('--check')) {
  require(file);
  const s = L.initState(lv);
  L.simulate(lv, s, L.route, L.route.length + 2000);
  if (!s.finished) { console.error(`stored route fails at beat ${(s.t / L.BEAT).toFixed(2)} (${s.cause})`); process.exit(1); }
  console.log(`stored route finishes the level (${L.route.length} steps)`);
  process.exit(0);
}
// Solve section by section (the search restarts at each boundary).
const bounds = [0, ...lv.sections.map(s => s.beat).filter(b => b > 0), lv.endBeat];
let st = L.initState(lv);
const all = [];
const t0 = Date.now();
for (let i = 0; i + 1 < bounds.length; i++) {
  // Search three beats past the boundary so the state carried into the next
  // section is not already doomed, then keep the route up to the boundary.
  const goal = L.xAt(lv, Math.min(lv.endBeat, bounds[i + 1] + 3) * L.BEAT);
  const keepUntil = bounds[i + 1] * L.BEAT;
  // Coarse input first (a change at most every 50 ms) for a human-looking
  // route; finer only if a section needs it.
  let r = null;
  for (const every of [12, 6, 2]) { r = S.solve(lv, st, goal, { every }); if (r && !r.failed) break; }
  if (!r || r.failed) { console.error(`no route through beats ${bounds[i]}-${bounds[i + 1]}; stuck near beat ${(r.t / L.BEAT).toFixed(2)}`); process.exit(1); }
  let keep = 0;
  { const p = L.cloneState(st); while (keep < r.inputs.length && p.t < keepUntil) { L.step(lv, p, !!r.inputs[keep]); keep++; } }
  const part = r.inputs.slice(0, keep);
  st = S.replay(lv, st, part);
  for (const v of part) all.push(v);
  console.log(`beats ${bounds[i]}-${bounds[i + 1]}: ${((Date.now() - t0) / 1000).toFixed(1)} s`);
}
// Coast to the end with the button released.
const fin = L.cloneState(st);
while (!fin.finished && !fin.dead) { L.step(lv, fin, false); all.push(0); }
if (!fin.finished) { console.error('route dies after the last section'); process.exit(1); }
fs.writeFileSync(file, `// route.js: generated by tools/solve.js. One proven route through the level,
// as run lengths (base 36) of released and held steps, alternating.
'use strict';
(function (L) {
  const runs = '${encode(all)}';
  const out = [];
  let v = 0;
  for (const r of runs.split(',')) { const n = parseInt(r, 36); for (let i = 0; i < n; i++) out.push(v); v ^= 1; }
  L.route = Uint8Array.from(out);
})(globalThis.LUMINAL = globalThis.LUMINAL || {});
`);
console.log(`wrote ${file}: ${all.length} steps`);
