// tools/embed.js: wrap the game's Tin source as a script, so index.html can
// load it from disk (browsers will not fetch() a file:// URL). The page
// compiles it at start-up with the same compiler the tests use.
//   node tools/embed.js          write src/game.js
//   node tools/embed.js --check  fail if src/game.js is out of date
'use strict';
const fs = require('node:fs');
const path = require('node:path');
const src = fs.readFileSync(path.join(__dirname, '../game/breakout.tin'), 'utf8');
const out = path.join(__dirname, '../src/game.js');
const text = `// Generated by tools/embed.js from game/breakout.tin. Do not edit.\n'use strict';\n(globalThis.G2G || (globalThis.G2G = {})).gameSource = ${JSON.stringify(src)};\n`;
if (process.argv.includes('--check')) {
  if (!fs.existsSync(out) || fs.readFileSync(out, 'utf8') !== text) { console.error('src/game.js is stale: run node tools/embed.js'); process.exit(1); }
  console.log('src/game.js is up to date');
} else { fs.writeFileSync(out, text); console.log(`wrote src/game.js (${src.length} characters)`); }
